name: github pages

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install --ignore-engines # TODO: 根本的に解決する方法を確認する
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: deploy --ignore-engines # TODO: 根本的に解決する方法を確認する
