name: github pages

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      run: git config user.email "heppokofrontend@gmail.com"
      run: git config user.name "heppokofrontend"
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: deploy
      run: yarn deploy
